services:
  # --- Contenedor de Prometheus (Almacenamiento de datos) ---
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alert-manager/rules.yml:/etc/prometheus/rules.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--storage.tsdb.retention.size=7GB'
      - '--storage.tsdb.wal-compression'
    ports:
      - "9090:9090"
    networks:
      - monitoring_network

  # --- Contenedor de Grafana (Dashboards) ---
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards_json:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring_network

  # --- Contenedor del Gestor de Alarmas ---
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    user: root
    ports:
      - "9093:9093"
    volumes:
      - ./alert-manager:/etc/alert-manager
      - alertmanager_data:/alert-manager
    command:
      - '--config.file=/etc/alert-manager/config.yml'
      - '--storage.path=/alert-manager'
    restart: unless-stopped
    networks:
      - monitoring_network

  # --- Recolector de Metricas del Sistema Operativo ---
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    network_mode: "host" 
    pid: "host"
    volumes:
      - '/:/host:ro,rslave'
    command:
      - '--path.rootfs=/host'
      - '--web.listen-address=192.168.4.210:9100'

  # --- Recolector de Datos del Hardware por BMC ---
  ipmi-exporter:
    build:
      context: ./ipmi-exporter
      dockerfile: Dockerfile
    container_name: ipmi-exporter
    restart: unless-stopped
    network_mode: "host"
    privileged: true
    devices:
      - /dev/ipmi0:/dev/ipmi0
    command:
      - 'ipmi_exporter'
      - '--config.file=/config/ipmi.yml'
      - '--web.listen-address=192.168.4.210:9290'

networks:
  monitoring_network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  alertmanager_data:
