global:
  scrape_interval: 15s
  evaluation_interval: 15s

# --- Conexion con Alertmanager ---
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['192.168.4.210:9093']

# --- Reglass de las Alertas ---
rule_files:
- "/etc/prometheus/alert-manager/rules.yml"

# --- Configuracion de Exportadores de los Equipos ---
scrape_configs:
  # Prometheus (Monitoreo propio)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Metricas de SO (Node Exporter)
  - job_name: 'os-metrics'
    static_configs:
      # Headnode
      - targets: ['192.168.4.210:9100'] 
        labels:
           instance: 'headnode'
      # Workers
      #- targets: ['192.168.4.211:9100']
      #  labels:
      #     instance: 'worker-01'
      - targets: ['192.168.4.212:9100']
        labels:
           instance: 'worker-02'
      #- targets: ['192.168.4.213:9100']
      #  labels:
      #     instance: 'worker-03'
      #- targets: ['192.168.4.214:9100']
      #  labels:
      #     instance: 'worker-04'

  # Metricas de Hardware (IPMI Exporter)
  - job_name: 'hw-metrics'
    metrics_path: /metrics
    scrape_interval: 60s
    scrape_timeout: 30s
    static_configs:
      # Headnode
      - targets: ['192.168.4.210:9290']
        labels:
           instance: 'headnode'
      # Workers
      #  - targets: ['192.168.4.211:9290']
      #    labels:
      #       instance: 'worker-01'
      - targets: ['192.168.4.212:9290']
        labels:
           instance: 'worker-02'
      # - targets: ['192.168.4.213:9290']
      #   labels:
      #      instance: 'worker-03'
      # - targets: ['192.168.4.214:9290']
      #   labels:
      #      instance: 'worker-04'

  # Estado de los nodos (Encendido - Apagado) via RedFish
  - job_name: 'node-state'
    metrics_path: /health
    scrape_interval: 2m
    scrape_timeout: 90s
    params:
      job: ['redfish-metrics']
    static_configs:
      # Headnode
      - targets: ['192.168.1.210']
        labels:
          friendly_name: 'headnode'
      # Workers
      - targets: ['192.168.1.212']
        labels:
          friendly_name: 'worker-02'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: bmc_ip
      - source_labels: [friendly_name]
        target_label: instance
      - target_label: __address__
        replacement: redfish-exporter:9220
