global:
  scrape_interval: 15s
  evaluation_interval: 15s

# --- Conexion con Alertmanager ---
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']

# --- Reglass de las Alertas ---
rule_files:
- "rules.yml"

# --- Configuracion de Exportadores de los Equipos ---
scrape_configs:
  # Prometheus (Monitoreo propio)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Metricas de SO (Node Exporter)
  - job_name: 'os-metrics'
    static_configs:
      # Headnode
      - targets: ['192.168.4.210:9100'] 
        labels:
           instance: 'headnode'
      # Workers
      #- targets: ['192.168.4.211:9100']
      #  labels:
      #     instance: 'worker-01'
      - targets: ['192.168.4.212:9100']
        labels:
           instance: 'worker-02'
      #- targets: ['192.168.4.213:9100']
      #  labels:
      #     instance: 'worker-03'
      #- targets: ['192.168.4.214:9100']
      #  labels:
      #     instance: 'worker-04'

  # Metricas de Hardware (IPMI Exporter)
  - job_name: 'hw-metrics'
    metrics_path: /metrics
    scrape_interval: 60s
    scrape_timeout: 30s
    static_configs:
      # Headnode
      - targets: ['192.168.4.210:9290']
        labels:
           instance: 'headnode'
      # Workers
      #  - targets: ['192.168.4.211:9290']
      #    labels:
      #       instance: 'worker-01'
      - targets: ['192.168.4.212:9290']
        labels:
           instance: 'worker-02'
      # - targets: ['192.168.4.213:9290']
      #   labels:
      #      instance: 'worker-03'
      # - targets: ['192.168.4.214:9290']
      #   labels:
      #      instance: 'worker-04'

