{
 "title": "Monitoreo del Uso del Hardware del Datacore",
 "tags": [ "NODE EXPORTER" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Nodos",
    "query": {
     "query": "label_values(node_uname_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ESTADO DE LOS NODE-EXPORTERS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (instance) (up{job=\"os-metrics\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CONSUMO DE CPU, RAM Y DISCO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "USO ACTUAL DE CPU",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 4, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$instance\"}[5m])) * 100)",
       "legendFormat": "CPU"
      }
     ]
    },
    {
     "title": "HISTORICO DE USO DE CPU",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 20, "x": 4, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$instance\"}[5m])) * 100)",
       "legendFormat": "Uso de CPU"
      },
      {
       "expr": "avg by (instance) (rate(node_cpu_seconds_total{mode=\"system\", instance=~\"$instance\"}[5m])) * 100",
       "legendFormat": "System"
      },
      {
       "expr": "avg by (instance) (rate(node_cpu_seconds_total{mode=\"iowait\", instance=~\"$instance\"}[5m])) * 100",
       "legendFormat": "IO Wait"
      }
     ]
    },
    {
     "title": "USO ACTUAL DE RAM",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 4, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$instance\"} / node_memory_MemTotal_bytes{instance=~\"$instance\"})) * 100",
       "legendFormat": "RAM"
      }
     ]
    },
    {
     "title": "HISTORICO DE USO DE RAM",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 20, "x": 4, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"} - node_memory_MemAvailable_bytes{instance=~\"$instance\"}",
       "legendFormat": "RAM Usada"
      },
      {
       "expr": "node_memory_Buffers_bytes{instance=~\"$instance\"}",
       "legendFormat": "Memory Buffers"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=~\"$instance\"}",
       "legendFormat": "Cache Memory"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"}",
       "legendFormat": "RAM Total"
      }
     ]
    },
    {
     "title": "USO ACTUAL DE DISCOS",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 14, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$instance\", mountpoint=~\"^(/|/home|/boot|/tmp|/var)$\"} / node_filesystem_size_bytes{instance=~\"$instance\", mountpoint=~\"^(/|/home|/boot|/tmp|/var)$\"}) * 100)",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "DETALLE EXACTO DE PARTICIONES",
     "type": "table",
     "gridPos": { "h": 9, "w": 10, "x": 14, "y": 24 },
     "targets": [
      {
       "expr": "sum by (mountpoint) (node_filesystem_size_bytes{instance=~\"$instance\", mountpoint=~\"^(/|/home|/boot|/tmp|/var)$\"})"
      },
      {
       "expr": "sum by (mountpoint) (node_filesystem_size_bytes{instance=~\"$instance\", mountpoint=~\"^(/|/home|/boot|/tmp|/var)$\"} - node_filesystem_avail_bytes{instance=~\"$instance\", mountpoint=~\"^(/|/home|/boot|/tmp|/var)$\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "TRAFICO DE RED DE LAS INTERFACES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "TRAFICO DE RED - eno1",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{instance=~\"$instance\", device=\"eno1\"}[5m])",
       "legendFormat": "Descarga (In)"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=~\"$instance\", device=\"eno1\"}[5m])",
       "legendFormat": "Subida (Out)"
      }
     ]
    },
    {
     "title": "TRAFICO DE RED - eno1.2",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{instance=~\"$instance\", device=\"eno1.2\"}[5m])",
       "legendFormat": "Descarga (In)"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=~\"$instance\", device=\"eno1.2\"}[5m])",
       "legendFormat": "Subida (Out)"
      }
     ]
    },
    {
     "title": "TRAFICO DE RED - eno1.4",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{instance=~\"$instance\", device=\"eno1.4\"}[5m])",
       "legendFormat": "Descarga (In)"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=~\"$instance\", device=\"eno1.4\"}[5m])",
       "legendFormat": "Subida (Out)"
      }
     ]
    },
    {
     "title": "TRAFICO DE RED - eno3",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{instance=~\"$instance\", device=\"eno3\"}[5m])",
       "legendFormat": "Descarga (In)"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=~\"$instance\", device=\"eno3\"}[5m])",
       "legendFormat": "Subida (Out)"
      }
     ]
    },
    {
     "title": "TRAFICO DE RED - eno4",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{instance=~\"$instance\", device=\"eno4\"}[5m])",
       "legendFormat": "Descarga (In)"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=~\"$instance\", device=\"eno4\"}[5m])",
       "legendFormat": "Subida (Out)"
      }
     ]
    }
   ]
  },
  {
   "title": "RENDIMIENTO DEL DISCO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "THROUGHPUT DEL DISCO",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_disk_read_bytes_total{instance=~\"$instance\", device!~\"loop.*|ram.*\"}[5m]))",
       "legendFormat": "Lectura (Read)"
      },
      {
       "expr": "sum by (instance) (rate(node_disk_written_bytes_total{instance=~\"$instance\", device!~\"loop.*|ram.*\"}[5m]))",
       "legendFormat": "Escritura (Write)"
      }
     ]
    },
    {
     "title": "OPERACIONES DE DISCO",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_disk_reads_completed_total{instance=~\"$instance\", device!~\"loop.*|ram.*\"}[5m]))",
       "legendFormat": "Lecturas (Reads/s)"
      },
      {
       "expr": "sum by (instance) (rate(node_disk_writes_completed_total{instance=~\"$instance\", device!~\"loop.*|ram.*\"}[5m]))",
       "legendFormat": "Escrituras (Writes/s)"
      }
     ]
    }
   ]
  },
  { "title": "ESTADO DEL SISTEMA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CARGA DEL SISTEMA (Load Average)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance\"}",
     "legendFormat": "1 Minute Average"
    },
    {
     "expr": "node_load5{instance=~\"$instance\"}",
     "legendFormat": "5 Minute Average"
    },
    {
     "expr": "node_load15{instance=~\"$instance\"}",
     "legendFormat": "15 Minute Average"
    }
   ]
  },
  {
   "title": "INTERRUPCIONES DEL SISTEMA (Interrupts)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_intr_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "Interrupts"
    }
   ]
  }
 ]
}