{
 "title": "Monitoreo del Estado del Hardware del Datacore",
 "tags": [ "IPMI EXPORTER" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Nodos",
    "query": {
     "query": "label_values(ipmi_up, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ESTADO DE LOS EQUIPOS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ipmi_chassis_power_state", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "ESTADO DE LOS EXPORTERS-IPMI",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max by (instance) (ipmi_up)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "HISTORICO DE TEMPERATURA DE LOS CPUS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "ipmi_temperature_celsius{instance=~\"$instance\", name=\"Temp\"}",
     "legendFormat": "CPU ID: {{id}}"
    }
   ]
  },
  {
   "title": "TEMPERATURAS ACTUALES",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_temperature_celsius{instance=\"$instance\"}",
     "legendFormat": "{{name}} - {{id}}"
    }
   ]
  },
  {
   "title": "HISTORICO DE TEMPERATURAS AMBIENTALES",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "ipmi_temperature_celsius{instance=~\"$instance\", name=\"Inlet Temp\"}",
     "legendFormat": "Temperatura del ambiente"
    },
    {
     "expr": "ipmi_temperature_celsius{instance=~\"$instance\", name=\"Exhaust Temp\"}",
     "legendFormat": "Temperatura del aire saliente"
    }
   ]
  },
  {
   "title": "HISTORICO DE CONSUMO ELECTRICO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ipmi_power_watts{instance=~\"$instance\"}",
     "legendFormat": "Consumo (Watts)"
    }
   ]
  },
  {
   "title": "CONSUMO ELEC. ACTUAL",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_power_watts{instance=~\"$instance\"}",
     "legendFormat": "Energía"
    }
   ]
  },
  {
   "title": "VELOCIDAD DE LOS VENTILADORES",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_fan_speed_rpm{instance=~\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "ESTADO FÍSICO DEL HARDWARE",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_chassis_drive_fault_state{instance=~\"$instance\"}",
     "legendFormat": "Estado de Discos"
    },
    {
     "expr": "ipmi_chassis_cooling_fault_state{instance=~\"$instance\"}",
     "legendFormat": "Estado de Ventilación"
    }
   ]
  }
 ]
}