global:
  smtp_smarthost: 'smtp.gmail.com:587' # Servidor SMTP de Gmail con puerto TLS (587)
  smtp_from: 'datacore.monitoring@gmail.com' # Direccion desde la cual se enviaran los correos
  smtp_auth_username: 'datacore.monitoring@gmail.com' # Usuario SMTP para autenticacion
  smtp_auth_password: 'lyza acui tngg btho'
  smtp_require_tls: true 

templates:
  - '/etc/alert-manager/email.tmpl'

route:
  receiver: 'gmail-receiver'
  group_wait: 1m
  group_interval: 3m
  repeat_interval: 15m

receivers:
  - name: 'gmail-receiver'
    email_configs:
     - to: 'andres.lujanf@pucp.edu.pe'
       send_resolved: true
       headers:
         Subject: '{{ template "custom_email.subject" . }}'
       html: '{{ template "custom_email.html" . }}'

inhibit_rules:
  # Silenciar Warnings si ya hay una alerta critica del mismo tipo en el mismo nodo
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['instance', 'type']
